<?php

namespace App\Http\Controllers;
<<<<<<< HEAD:app/Http/Controllers/BlogpController.php
use App\Models\Blogp;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
class BlogpController extends Controller
{
    //
    function addBlog(Request $req){
        $blog_post = new Blogp;
        $blog_post->title=$req->input('title');
        $blog_post->content=$req->input('content');
        $blog_post->slug=$this->generateSlug();
        $blog_post->image=$req->file('image')->store('products');
        $blog_post->save();
        return $blog_post;
    }
    function listBlog(){
        return Blogp::all();

    }
    public function generateSlug(){
        $slug = Str::random(10);
        while (Blogp::where('slug',$slug)->exists()){
            $slug = Str::random(10);
=======

use App\Http\Resources\BlogResource;
use App\Http\Requests\StoreBlogRequest;
use App\Http\Requests\UpdateBlogRequest;
use App\Models\Blog;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $query = Blog::query();

        $sortField = request("sort_field", 'created_at');
        $sortDirection = request("sort_direction", "desc");

        if (request("title")) {
            $query->where("title", "like", "%" . request("title") . "%");
>>>>>>> b87ae96 (changes):app/Http/Controllers/BlogController.php
        }
        if (request("status")) {
            $query->where("status", request("status"));
        }

        $blogs = $query->orderBy($sortField, $sortDirection)
            ->paginate(10)
            ->onEachSide(1);

        return inertia("Blog/Index", [
            "blogs" => BlogResource::collection($blogs),
            'queryParams' => request()->query() ?: null,
            'success' => session('success'),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return inertia("Blog/Create");
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreBlogRequest $request)
    {
        $data = $request->validated();
        /** @var $image \Illuminate\Http\UploadedFile */
        $image = $data['image'] ?? null;
        
        if ($image) {
            $data['image_path'] = $image->store('blog/' . Str::random(), 'public');
        }

        // Create the blog post. The slug will be auto-generated by the model.
        Blog::create($data);

        return to_route('blog.index')
            ->with('success', 'Blog post was created');
    }

    /**
     * Display the specified resource.
     */
    public function show(Blog $blog)
    {
        return inertia('Blog/Show', [
            'blog' => new BlogResource($blog),
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Blog $blog)
    {
        return inertia("Blog/Edit", [
            'blog' => new BlogResource($blog),
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateBlogRequest $request, Blog $blog)
    {
        $data = $request->validated();
        $image = $data['image'] ?? null;
        if ($image) {
            if ($blog->image_path) {
                Storage::disk('public')->deleteDirectory(dirname($blog->image_path));
            }
            $data['image_path'] = $image->store('blog/' . Str::random(), 'public');
        }

        // Update the blog post. The slug will be auto-generated by the model if the title changes.
        $blog->update($data);

        return to_route('blog.index')
            ->with('success', "Blog post \"$blog->title\" was updated");
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Blog $blog)
    {
        $title = $blog->title;
        $blog->delete();
        if ($blog->image_path) {
            Storage::disk('public')->deleteDirectory(dirname($blog->image_path));
        }
        return to_route('blog.index')
            ->with('success', "Blog post \"$title\" was deleted");
    }
}
